# Generated by Django 3.0.7 on 2020-06-18 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200618_2132'),
        ('main_app', '0002_auto_20200618_1905'),
    ]

    operations = [
    ]
