# Generated by Django 3.0.7 on 2020-06-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200623_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imageURL',
            field=models.ImageField(blank=True, default='https://thispersondoesnotexist.com/image', upload_to='profile_image'),
        ),
    ]
