# Generated by Django 3.0.7 on 2020-06-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merge_20200618_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imageURL',
            field=models.CharField(default='', max_length=250),
        ),
    ]
