# Generated by Django 3.0.7 on 2020-06-23 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200623_2131'),
        ('main_app', '0003_auto_20200623_1853'),
    ]

    operations = [
    ]
