# Generated by Django 3.0.7 on 2020-06-19 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200619_1700'),
        ('main_app', '0004_auto_20200619_1658'),
    ]

    operations = [
    ]
