# Generated by Django 3.0.7 on 2020-06-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200623_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imageURL',
            field=models.ImageField(blank=True, default='profile_image/default_img.jpg', upload_to='profile_image'),
        ),
    ]
